"""Medical product research agent foundation package."""

from medical_research_agent.config import AppSettings, get_settings
from medical_research_agent.connectors import (
    ClinicalTrialsConnector,
    ConnectorError,
    CrossrefConnector,
    DuckDuckGoHTMLSearchConnector,
    OpenFDA510kConnector,
    PubMedConnector,
    SearchRequest,
    SemanticScholarConnector,
    SourceConnector,
    URLSourceConnector,
)
from medical_research_agent.llm import (
    LLMClient,
    LLMMessage,
    LLMRequest,
    LLMResponse,
    MockLLMClient,
    OpenAICompatibleLLMClient,
    get_llm_client,
)
from medical_research_agent.io import write_model_json
from medical_research_agent.parsers import (
    DocumentParseError,
    LocalFileIngestor,
    PDFParser,
    WebPageParser,
    detect_document_format,
)
from medical_research_agent.schemas import (
    Claim,
    EvidenceItem,
    FigureAsset,
    FigureKind,
    FigureStatus,
    ParsedDocument,
    ProductSpec,
    ReportArtifact,
    ReportSection,
    ReportTemplate,
    ReportTemplateBlock,
    ResearchTask,
    SourceRecord,
    TemplateBlockKind,
)

__all__ = [
    "AppSettings",
    "Claim",
    "ClinicalTrialsConnector",
    "ConnectorError",
    "CrossrefConnector",
    "DocumentParseError",
    "DuckDuckGoHTMLSearchConnector",
    "EvidenceItem",
    "FigureAsset",
    "FigureKind",
    "FigureStatus",
    "LLMClient",
    "LLMMessage",
    "LLMRequest",
    "LLMResponse",
    "LocalFileIngestor",
    "MockLLMClient",
    "OpenAICompatibleLLMClient",
    "OpenFDA510kConnector",
    "PDFParser",
    "ParsedDocument",
    "ProductSpec",
    "PubMedConnector",
    "ReportArtifact",
    "ReportSection",
    "ReportTemplate",
    "ReportTemplateBlock",
    "ResearchTask",
    "SearchRequest",
    "SemanticScholarConnector",
    "SourceRecord",
    "SourceConnector",
    "TemplateBlockKind",
    "URLSourceConnector",
    "WebPageParser",
    "detect_document_format",
    "get_settings",
    "get_llm_client",
    "write_model_json",
]
